print('='*12)
l = float(input('Digite a largura da parede: '))
a = float(input('Digite a altura da parede: '))
print('Você vai precisar de {}L de tinta para pintar {}m² de parede'.format((l*a)/2, (l*a)))
print('='*12)
